catchphrase_str = input("Please enter a catchphrase :")
print(f"[   {catchphrase_str.upper()}  ]" )
print(f"[   {catchphrase_str}  ]")
print(f"[   {catchphrase_str.rstrip()}   ]")
print(f"[   {catchphrase_str.lstrip()}   ]")